/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import DAO.HeroiDAO;
import DAO.SalvamentosDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Heroi;
import model.Salvamentos;
import util.JDBCUtil;

/**
 *
 * @author fabricio
 */
public class JanelaSalvamentos extends javax.swing.JFrame {

    SalvamentosDAO dao = new SalvamentosDAO();
    boolean bancoLigado = false;


    public JanelaSalvamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        btn_primeiro = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        jTF_id = new javax.swing.JTextField();
        jTF_heroi = new javax.swing.JTextField();
        jTF_qtsalvamento = new javax.swing.JTextField();
        btn_abrebanco = new javax.swing.JButton();
        btn_inserir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        idDias = new javax.swing.JButton();
        idDias1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("ID do dia que foi realizado o salvamento:");

        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("ID do heroi que realizou o salvamento:");

        label6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label6.setText("Quantidade de salvamentos que ele realizou neste dia:");

        btn_primeiro.setLabel("Primeiro");
        btn_primeiro.setName("btnprimeiro"); // NOI18N
        btn_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeiroActionPerformed(evt);
            }
        });

        btn_anterior.setLabel("Anterior");
        btn_anterior.setName("btnanterior"); // NOI18N
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_proximo.setLabel("Próximo");
        btn_proximo.setName("btnproximo"); // NOI18N
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        btn_ultimo.setLabel("Último");
        btn_ultimo.setName("btnultimo"); // NOI18N
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        btn_abrebanco.setLabel("Abre BD");
        btn_abrebanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrebancoActionPerformed(evt);
            }
        });

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idDias.setText("Ver ID Dias Validos");
        idDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDiasActionPerformed(evt);
            }
        });

        idDias1.setText("Ver ID Herois Validos");
        idDias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDias1ActionPerformed(evt);
            }
        });

        jLabel1.setText("(0-100)");

        jButtonAjuda.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAjuda.setText("ajuda");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btn_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label3)
                                            .addComponent(label1))
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label6)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_heroi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_qtsalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idDias1)
                                    .addComponent(idDias)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAjuda)))))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_abrebanco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_primeiro)
                    .addComponent(btn_anterior)
                    .addComponent(btn_proximo)
                    .addComponent(btn_ultimo))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_heroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDias1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_qtsalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jButtonAjuda)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_abrebanco)
                    .addComponent(btn_inserir)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_novo)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeiroActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
        try{
          if(JDBCUtil.goFirst(dao.getRsdados())){
            System.out.println("primeiro elemento acessado!");
            ExibeRegistro(dao.getSalvamentos());
          }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Ja esta no primeiro.");
        }
            
    }//GEN-LAST:event_btn_primeiroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
        try{
          if(JDBCUtil.goPrevious(dao.getRsdados())){
              System.out.println("elemento retornado com sucesso");
              ExibeRegistro(dao.getSalvamentos());
          }
          else{
              JOptionPane.showMessageDialog(this, "Nao tem elemento anterior.");
          }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR.");
        }
            
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
        try{
          if(JDBCUtil.goNext(dao.getRsdados())){
              System.out.println("proximo elemento com sucesso");
              ExibeRegistro(dao.getSalvamentos());
          }
          else{
              JOptionPane.showMessageDialog(this, "Nao tem proximo elemento.");
          }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR.");
        }
            
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
        try{
          if(JDBCUtil.goLast(dao.getRsdados())){
            System.out.println("ultimo elemento acessado!");
            ExibeRegistro(dao.getSalvamentos()); 
          }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Ja esta no ultimo elemento.");
        }
             
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_abrebancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrebancoActionPerformed
        if (dao.CriaConexao()) {
            if (dao.ConsultarTodos()) {
                bancoLigado = true;
                try {
                    if(dao.getRsdados().first()){
                        ExibeRegistro(dao.getSalvamentos());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(JanelaSalvamentos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_abrebancoActionPerformed

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
 
            Salvamentos salvamento = CarregaSalvamento();
            if (dao.Inserir(salvamento)) {
                JOptionPane.showMessageDialog(this, "Salvamento inserido com sucesso. Veja o relatorio para melhor visualização");
            }
            else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir Salvamento.\n"
                    + "verifique se já não existe este mesmo heroi, neste mesmo dia já cadastrado\n"
                    + "se ja houver, use a função alterar para somar a quantidade de salvamentos realizados neste dia\n"
                    + "caso contrario, pode ser o banco de dados, verifique o log");
            }

    }//GEN-LAST:event_btn_inserirActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        jTF_id.setText("");
        jTF_heroi.setText("");
        jTF_qtsalvamento.setText("");
        jTF_id.requestFocus();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dao.FechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
       
        Salvamentos salvamento = CarregaSalvamento();
        if (dao.Alterar(salvamento)) {
            JOptionPane.showMessageDialog(this, "Salvamento alterado com sucesso.");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar Salvamento.");
        }
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
       if(bancoEstaAberto(bancoLigado) == false)
            return;
       
        Salvamentos salvamento = CarregaSalvamento();
        if (dao.Excluir(salvamento)) {
            JOptionPane.showMessageDialog(this, "Salvamento excluído com sucesso.");
            btn_primeiroActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir Salvamento.");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDiasActionPerformed
        JOptionPane.showMessageDialog(this, "ID Válido:\n"
                                            + "1 = Segunda-feira. \n2 = Terça-Feira \n3 = Quarta-Feira \n4 = Quinta-Feira\n5 = Sexta-Feira \n6 = Sábado\n7 = Domingo \n");
    }//GEN-LAST:event_idDiasActionPerformed

    private void idDias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDias1ActionPerformed
                HeroiDAO daoh = new HeroiDAO();
                String str = "herois cadastrados:\n";
                daoh.CriaConexao();
                try {
                   daoh.ConsultarTodos();
                    if(daoh.getRsdados().first()){
                        while(daoh.getRsdados().next()){
                            str = str + "id: "+String.valueOf(daoh.getHeroi().getId())
                            +"   heroi: "+(daoh.getHeroi().getNome())
                            +"\n";
                        }
                        JOptionPane.showMessageDialog(this, str);
                    }
                    else{
                        System.out.println("ATENÇÃO:");
                        System.out.println("nenhum heroi cadastrado no sistema.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                

                    
    }//GEN-LAST:event_idDias1ActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        JOptionPane.showMessageDialog(this, "Ajuda:\n"
                + "considerando que o ID dia seja 1 = segunda feira\n"
                + "e ID heroi 3 = batman\n"
                + "e quantidade salvamento = 5\n"
                + "voce estaria cadastrando que: o batman realizou 5 salvamentos na segunda feira\n");
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaSalvamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaSalvamentos().setVisible(true);
            }
        });
    }

    public void ExibeRegistro(Salvamentos salvamento) {
        jTF_id.setText(String.valueOf(salvamento.getId()));
        jTF_heroi.setText(String.valueOf(salvamento.getHeroi()));
        jTF_qtsalvamento.setText(String.valueOf(salvamento.getQtSalvamento()));
    }

    public Salvamentos CarregaSalvamento() {
        Salvamentos salvamento = null;
        int id = Integer.valueOf(jTF_id.getText());
        int heroi = Integer.valueOf(jTF_heroi.getText());
        int qtSalvamento = Integer.valueOf(jTF_qtsalvamento.getText());
        salvamento = new Salvamentos(id, heroi, qtSalvamento);
        return salvamento;
    }
    
public boolean bancoEstaAberto(boolean banco){
        if(banco == false){
            JOptionPane.showMessageDialog(this, "Ligue o banco de dados primeiro!!");
            return false;
        }
        return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrebanco;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_primeiro;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JButton idDias;
    private javax.swing.JButton idDias1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTF_heroi;
    private javax.swing.JTextField jTF_id;
    private javax.swing.JTextField jTF_qtsalvamento;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label6;
    // End of variables declaration//GEN-END:variables
}

